services:
  investigator_assistant:
    build: .
    container_name: investigator_assistant
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
